services:
  nginx:
    image: nginxserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    develop:
      watch: 
        - action: rebuild
          path: .
    